name: build
run-name:
on: [push]
jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install poetry
        run: pip install poetry -U
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'poetry'
      - name: Build
        run: poetry build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          path: dist
