name: runtests
run-name:
on: [push, pull_request]
jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install poetry
        run: python -m pip install --upgrade pip setuptools wheel poetry
      - name: Poetry install other dependencies
        run: poetry install
      - name: Run test suite
        run: poetry run python runtests.py
