name: test
on:
  push:
    paths:
      - "**.py"
      - "poetry.lock"
      - ".github/workflows/test.yml"
  pull_request:
    paths:
      - "**.py"
      - "poetry.lock"
      - ".github/workflows/test.yml"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install poetry
        run: pip install poetry -U
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: "poetry"
      - name: Poetry install other dependencies
        run: poetry install
      - name: Run test suite
        run: poetry run python runtests.py
